DROP TABLE IF EXISTS USER cascade;

CREATE TABLE USER
(
    ID        INT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    ACCOUNT_ID INT,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);


DROP TABLE IF EXISTS ACCOUNT cascade;
CREATE TABLE ACCOUNT
(
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT_OF_MONEY INT     NOT NULL,
    ACCOUNT_NUM     VARCHAR NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

insert into ACCOUNT (AMOUNT_OF_MONEY, ACCOUNT_NUM) values (1000, 1);
insert into ACCOUNT (AMOUNT_OF_MONEY, ACCOUNT_NUM) values (1000, 2);
insert into ACCOUNT (AMOUNT_OF_MONEY, ACCOUNT_NUM) values (1000, 3);
insert into ACCOUNT (AMOUNT_OF_MONEY, ACCOUNT_NUM) values (1000, 4);

INSERT INTO USER(NAME, LAST_NAME, ACCOUNT_ID) VALUES ('Ivan', 'Ivanov', 1);
INSERT INTO USER(NAME, LAST_NAME, ACCOUNT_ID) VALUES ('Dmitriy', 'Petrov', 2);
INSERT INTO USER(NAME, LAST_NAME, ACCOUNT_ID) VALUES ('Zinaida', 'Kulikova', 3);
INSERT INTO USER(NAME, LAST_NAME, ACCOUNT_ID) VALUES ('Vladimir', 'Putin', 4);

update ACCOUNT set  USER_ID = 1 where ID = 1;
update ACCOUNT set  USER_ID = 2 where ID = 2;
update ACCOUNT set  USER_ID = 3 where ID = 3;
update ACCOUNT set  USER_ID = 4 where ID = 4;



